# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchoice',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
