# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userchoice_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchoice',
            name='selected',
        ),
    ]
