# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_userchoice_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchoice',
            name='choice_text',
            field=models.CharField(default=' ', max_length=300),
        ),
    ]
