# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180211_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchoice',
            name='choice_text',
            field=models.CharField(default='null', max_length=300),
        ),
    ]
