# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180211_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='college',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
