# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20180123_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='mark',
            field=models.IntegerField(),
        ),
    ]
