# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_userchoice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Result',
            new_name='UserProfile',
        ),
    ]
