# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_choice',
        ),
        migrations.AddField(
            model_name='choice',
            name='correct_choice',
            field=models.BooleanField(default=False),
        ),
    ]
