# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='selected',
        ),
    ]
